apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springbootapp
spec:
  selector:
    matchLabels:
      app: k8s-springbootapp
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-springbootapp
    spec:
      containers:
        - name: k8s-springbootapp
          image: springbootapp:4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


